### ISSUE TITLE
Add more dungeons, rooms or floors 🤣 

### ISSUE THREAD

**Issue by ming-tsai** [MakeContributions/markdown-dungeon#1]
It'd be awesome to have a lot of the dungeons, rooms, or floors, so the game could be more fun 😜

🐞 Problem
Currently, we have only a bunch of dungeons, rooms, or floors in the project

🎯 Goal
Have a lot of dungeons, rooms, or floors from the diverse games.

💡 Possible solutions
Add new a new dungeon, rooms, or floors.

**How to make it?**
Check out [Contribution Guidelines](https://github.com/MakeContributions/markdown-dungeon#contribution-guidelines)

📋 Steps to solve the problem

1. Comment below about what you've started working on.
2. Add, commit, push your changes
3. Submit a pull request and add this in comments - Addresses #
4. Ask for a review in the comments section of pull request
5. Celebrate your contribution to this project 🎉

**Comment by aUsefulMethod** [comment]
Looking to contribute. Should I create a PR to add some option to a floor?

**Comment by ming-tsai** [comment]
Yes @aUsefulMethod could you helping me?

**Comment by aUsefulMethod** [comment]
yes I would love to! I already cloned the repo.

**Comment by Dexters-Hub** [comment]
This is so cool. I would love to contribute.

**Comment by ming-tsai** [comment]
Hi @Dexters-Hub,
I will wait for your contribution 😎

**Comment by Dexters-Hub** [comment]
@ming-tsai Added a pull request

**Comment by benmanuel12** [comment]
Hi, I'm new to this. I am going to try and add something.

**Comment by ming-tsai** [comment]
Hi @benmanuel12, I will wait for your contributions 😜😊

**Comment by benmanuel12** [comment]
@ming-tsai I think I submitted a pull request earlier.
I wasn't quite sure on how to phrase my additions.

**Comment by ming-tsai** [comment]
> @ming-tsai I think I submitted a pull request earlier.
> I wasn't quite sure on how to phrase my additions.

Yes, I saw it, and that is a nice work 💪

**Comment by aenyne** [comment]
Hi I added a path with a rabbit

**Comment by ming-tsai** [comment]
> Hi @ming-tsai I added a path with a rabbit

Okis I will check it out

**Comment by Dexters-Hub** [comment]
@ming-tsai There is no emojis showing in the path that was added by @aenyne

**Comment by ming-tsai** [comment]
> @ming-tsai There is no emojis showing in the path that was added by @aenyne 

Ok, but the contribution guidelines doesn't specify about emojis

**Comment by ming-tsai** [comment]
> @ming-tsai There is no emojis showing in the path that was added by @aenyne 

Ok, I will check it out

**Comment by aenyne** [comment]
Oh I see, what did I wrong? 😱

**Comment by Arsenic-ATG** [comment]
> Oh I see, what did I wrong? 😱

@aenyne it has been fixed in [this](https://github.com/MakeContributions/markdown-dungeon/pull/72) pull request now, you can check the [issue](https://github.com/MakeContributions/markdown-dungeon/issues/70) regarding the same.

**Comment by Poussinette** [comment]
I'd like to contribute! Does it count for hacktoberfest?

**Comment by Arsenic-ATG** [comment]
@Poussinette this repo is open for all to contribute, as far as Hacktoberfest is considered then according to [their guidelines](https://hacktoberfest.digitalocean.com/details) :- 

> Any pull request with the hacktoberfest-accepted label, submitted to any public GitHub repository, with or without the hacktoberfest topic, will be considered valid for Hacktoberfest.

so it will depend on the quality of PR and project owner ( @ming-tsai ) wether to count it for hacktober or not.👍

**Comment by ming-tsai** [comment]
Hi @Poussinette, I will wait your contributions 🤠😎

**Comment by PhilipWright96** [comment]
Hi @ming-tsai  - I've opened a quick PR for some extra rooms. https://github.com/MakeContributions/markdown-dungeon/pull/96. Lemme know if thats okay or if theres some changes I should make. Thanks!

**Comment by Poussinette** [comment]
@ming-tsai  I've opened this PR #97 . Please review and let me know. Thanks!

**Comment by ming-tsai** [comment]
> @ming-tsai I've opened this PR #97 . Please review and let me know. Thanks!

Nice work 🙌🙌

**Comment by LFsolar** [comment]
Can I contribute? I want to add a sub room

**Comment by ming-tsai** [comment]
> Can I contribute? I want to add a sub room

Of course, I will wait for your contributions

**Comment by ming-tsai** [comment]
Thanks for the contributions for:
@hayat-tamboli
@caspero-62 
@samuelorobosa 
@UnicycleDumpTruck 
@Arsenic-ATG 
@VJ1224
@aUsefulMethod 


I will open another we the same issues and close every 10 pull request of adding more rooms or floors, so you could have a contribution count on Github.
