### ISSUE TITLE
Proofread pages

### ISSUE THREAD

**Issue by FukurouMakoto** [MakeContributions/markdown-dungeon#104]
Hi, 

I noticed that some of the pages in the English project have grammatical errors. Would it be okay if I go ahead and edit them?

**Comment by ming-tsai** [comment]
> Hi, 
> 
> I noticed that some of the pages in the English project have grammatical errors. Would it be okay if I go ahead and edit them?

Hi @FukurouMakoto, yes.
I will wait for your contribution 😎
