### ISSUE TITLE
No Message Shows For An Option in the Game

### ISSUE THREAD

**Issue by paulsonjpaul** [MakeContributions/markdown-dungeon#107]
Hello,

I just explored this repo and played the game. But, I found a bug. 

This is the way I played:

Start a new game > I choose you, the normal dungeon > Begin Your Journey > Find a Way Out > Go Home > Something seems amiss, so you venture forth with an uneasiness of what may lie ahead > Sneak around and enter from the back?

And, when I click the last link, it gets me back to the Begin your Journey page. If I choose other options, it will show a message saying that I am dead. It would be nice if there is a similar message for this option as well.

Thanks!

**Comment by ming-tsai** [comment]
Hi @paulsonjpaul, maybe the author doesn't finished yet the path, so you could help him finish

**Comment by paulsonjpaul** [comment]
Ok. I will do it once I do something for #103 😀. Or any other friends can take this.

**Comment by paulsonjpaul** [comment]
As no one have taken this issue, I will take it and fix it.

**Comment by paulsonjpaul** [comment]
I have made a pull request related to this issue: #111 

Please review it.
