### ISSUE TITLE
Link not found

### ISSUE THREAD

**Issue by Codely-F** [MakeContributions/markdown-dungeon#115]
I started the game, i ended up in a page
where it shows like this
![image](https://user-images.githubusercontent.com/73823535/102043278-02060780-3dfa-11eb-95dd-477a14fe3ae0.png)
When i click the link it took me to 404 page of github.
Please take a note.

**Comment by paulsonjpaul** [comment]
Looks like the issue is with wrong relative url. If you want, you can fix it.

Just fork the repo, create a new branch, edit the WIP.md file. Change the link from `../../../README.md#contribution-guidelines` to `../../README.md#contribution-guidelines`

**Comment by paulsonjpaul** [comment]
Please make sure you read the contribution docs as well before doing this. It can be found in the readme file.

**Comment by Codely-F** [comment]
I read the docs and change the URL. it worked fine.

**Comment by paulsonjpaul** [comment]
Then you are ready to make a pull request 👍

**Comment by Codely-F** [comment]
in where?

**Comment by Codely-F** [comment]
I did it in the fork repo.

**Comment by paulsonjpaul** [comment]
Did you make a Pull Request? If not, please do it. Then only we can merge it into this repo.

**Comment by paulsonjpaul** [comment]
I see that you created a pull request in your fork. That is not the way of doing it. Please create a Pull Request again and make sure you point the `base` branch to this repo.

**Comment by ming-tsai** [comment]
Hi @Codely-F, is this issue is solved on #116 ?

**Comment by paulsonjpaul** [comment]
Right now the hyperlink points to #112 based on @Arsenic-ATG's PR. Nice job anyway @Codely-F .

**Comment by ming-tsai** [comment]
Ok, thanks @paulsonjpaul.
This issue will be closed, if the bug is persisted you could reopen it
