### ISSUE TITLE
Shouldn't We Add Translations

### ISSUE THREAD

**Issue by paulsonjpaul** [MakeContributions/markdown-dungeon#117]
Recently, there has been many commits to the `english` folder and fresh rooms and dungeons have been added. 

But, the new files have not been translated into portuguese (I think chinese is a seperate dungeon).

So, shouldn't we update the translations?

>Inviting some maintainers for their feedback: @ming-tsai, @Arsenic-ATG, @FukurouMakoto. Others are also welcome.

**Comment by ming-tsai** [comment]
Translate to another language will be as WIP dungeon, so the one understands portuguese could working on it

**Comment by paulsonjpaul** [comment]
Maybe you can let the person who translated know.

**Comment by ming-tsai** [comment]
Yes, maybe we could create the issue and the translate file

**Comment by Arsenic-ATG** [comment]
maybe let the people who know other languages create a whole new dungeon in their native language ( they may take inspiration from the english versions), like this it will be much easier for others to contribute in their native languages also and we don't have to keep all the languages in sync.

**Comment by Arsenic-ATG** [comment]
I think the thing which requires translation is the readme file ( containing contribution guidelines and dungeon structure ) so that everyone could understand it better.

**Comment by Codely-F** [comment]
Can I help you translate the readme file into [Tamil](https://en.wikipedia.org/wiki/Tamil_language)?

**Comment by paulsonjpaul** [comment]
> maybe let the people who know other languages create a whole new dungeon in their native language ( they may take inspiration from the english versions), like this it will be much easier for others to contribute in their native languages also and we don't have to keep all the languages in sync.

That's a good point. I think the dungeon in Chinese is completely different.

> I think the thing which requires translation is the readme file ( containing contribution guidelines and dungeon structure ) so that everyone could understand it better.
> 
> Edit :
> This might also be the one of the cause of people contributing a lot in english than other languages, as the guidlines are in that particular language only

That's true. @Arsenic-ATG, I see you are from India. If you know Hindi, you can help translate. (Even though I am also an Indian, I am not fluent in Hindi. My native language is [Malayalam](https://en.wikipedia.org/wiki/Malayalam))

This discussion is going really well. @ming-tsai, I think it will be good if you add a new issue welcoming others to translate this repository.

**Comment by Codely-F** [comment]
Then @paulsonjpaul why don't you translate the readme file into Malayalam?

**Comment by paulsonjpaul** [comment]
Ok @Codely-F. I will do it after it is translated into more popular languages

**Comment by Codely-F** [comment]
Sure

**Comment by paulsonjpaul** [comment]
@ming-tsai, I will close this issue for now and add a new issue welcoming new people to translate the documentations. Adding a new fresh issue is good, because if someone see our discussion, they might be confused.

**Comment by ming-tsai** [comment]
Ok @paulsonjpaul, I will looking for it
