### ISSUE TITLE
Open Source Projects/Repositories

### ISSUE THREAD

**Issue by akrish4** [MakeContributions/markdown-dungeon#118]
I would request for starting few new  repositories for open source contributions in DSA , python projects anyhting to encourage more open source developers and contributors.

**Comment by paulsonjpaul** [comment]
@ming-tsai, can you please look into this? Seems like @akrish4 is giving a suggestion to add new repos inside the MakeContributions organization.

**Comment by akrish4** [comment]
yes @paulsonjpaul , @ming-tsai  kindly look into this .

**Comment by ming-tsai** [comment]
Hi @akrish4,
Yes, I could create the repository, but please answer theses:
- Talk about the new project
- How will it left another contributed?
- Would you like make an example repository?
> You could make an example personal repository then transfer to another one

**Comment by akrish4** [comment]
- New  repos for DSA contributions , Programming language concepts like that for learning purpose and to improve ourselves , everyone interested in open source can contribute , understand and experience the working of  git , DSA.
- Interested people will contribute in it.
- Okay I can make a DSA repository and can transfer it to here ?

**Comment by ming-tsai** [comment]
Yes

**Comment by ming-tsai** [comment]
This issue is closed because we move to discussion #120
