### ISSUE TITLE
Charts for journey's

### ISSUE THREAD

**Issue by mamamia5x** [MakeContributions/markdown-dungeon#129]
These would be simple charts to show you the different pathways for a dungeon. 
This will be easier for developers to see what pathways lead to where.

**Comment by paulsonjpaul** [comment]
Can you please elaborate? How can we show this chart? By chart, did you mean something like a route map?

Another challenge would be to constantly update the chart so that it stays up to date with the dungeons when new floors and rooms are added.

**Comment by mamamia5x** [comment]
It is a route map, and it would make it so much easier to add more. I don't know what kinda site will host it, but https://excalidraw.com/ allows you to download the files.

**Comment by paulsonjpaul** [comment]
Let's wait for others' feedback.

> @ming-tsai, @Arsenic-ATG, @FukurouMakoto

**Comment by ming-tsai** [comment]
Hi @mamamia5x,
It's not bad idea, but if we create that the new contributors will be modify two sides, and it will be take long times to searching the rooms.
The purpose of the repo is they play the game and create a change.
So, I do not agree with you.

**Comment by FukurouMakoto** [comment]
Would be pretty interesting but I think it might be hard to develop for the same reasons @paulsonjpaul mentioned. 
I tried implementing something like this in a small text-based RPG I built with Python and it was a nightmare. 

It might be good for organization purposes but it would also mean that now we will have two things to update: our own levels as well as the this chart. 

Personally I could go either way. I like the idea but it's gonna have alot of challenges to implement.

**Comment by mamamia5x** [comment]
I'm currently almost finished, I just need to implement two more pathways. I'll reply with a photo when I'm done.

**Comment by mamamia5x** [comment]
![descision_tree](https://user-images.githubusercontent.com/57536929/103942153-8eec6a00-50f5-11eb-8a98-b8d3bda880e4.png)
@ming-tsai @FukurouMakoto 

#132

**Comment by ming-tsai** [comment]
> ![descision_tree](https://user-images.githubusercontent.com/57536929/103942153-8eec6a00-50f5-11eb-8a98-b8d3bda880e4.png)
> @ming-tsai @FukurouMakoto 
> 
> #132

I checked, nice work

**Comment by mamamia5x** [comment]
Thanks ;)
