### ISSUE TITLE
Add emoji to files

### ISSUE THREAD

**Issue by Arsenic-ATG** [MakeContributions/markdown-dungeon#13]
Every option/statement if possible should have emoji to make it more appealing to the players.

**Comment by ming-tsai** [comment]
Hi @Arsenic-ATG, nice idea, I will working on Chinese language, could you help me on English version?

**Comment by Arsenic-ATG** [comment]
@ming-tsai sure👍, 
I would be happy to help. You can leave English version to me

**Comment by ming-tsai** [comment]
Hi @Arsenic-ATG, done with the Chinese version

**Comment by Arsenic-ATG** [comment]
@ming-tsai english version is also updated .( [PR submitted](https://github.com/MakeContributions/markdown-dungeon/pull/20) )

**Comment by ming-tsai** [comment]
PR #20 is merged, thanks for your contribution 🥇
