### ISSUE TITLE
What is going on with folder number 9 in English Normal Dungeon?

### ISSUE THREAD

**Issue by mamamia5x** [MakeContributions/markdown-dungeon#130]
![image](https://user-images.githubusercontent.com/57536929/103930253-1204c480-50e4-11eb-8be6-882a9ad41906.png)

While I was working on the decision tree, I came upon folder number 9. It is just an infinite loop hole, with the explore room number not being completed. That page itself has nothing in it is just
```
# Under Construction
``` 
so, there is no way to get out of it, or by dying. But is there a way just to organize it, the doors are just to excessive, they all lead back to the same place. Most are outdated as well, they don't have any emoji's and are pretty long.

**Comment by ming-tsai** [comment]
Yes I will change it to point to another file [english/normal-dungeon/4/0.md](https://github.com/MakeContributions/markdown-dungeon/blob/master/english/normal-dungeon/4/0.md)

**Comment by ming-tsai** [comment]
@mamamia5x fix on #131, check it out and let me know
