### ISSUE TITLE
Expand Floor 2 in english/normal-dungeon

### ISSUE THREAD

**Issue by VJ1224** [MakeContributions/markdown-dungeon#16]
Creating this issue. Will work on it myself.

TODO:

- [x] Create story for floor 2

- [x] Create rooms for floor 2

- [x] Add link to reach floor 3

**Comment by ming-tsai** [comment]
Ok

**Comment by aUsefulMethod** [comment]
Good idea VJ. A really put-together story would make choosing options more rewarding.
