### ISSUE TITLE
No way to go back to home page 

### ISSUE THREAD

**Issue by hkumar0132** [MakeContributions/markdown-dungeon#163]
I would like to add a way to go back to the homepage from any game. I am thinking of a button with href on the top left of web page.

**Comment by AkshatJindal1** [comment]
Hi I would like to work on this feature. I have added a home button on each page which user can use to goto the main page from any screen he wants.

Here is an example screenshot
<img width="1680" alt="Screenshot 2021-06-22 at 8 39 24 PM" src="https://user-images.githubusercontent.com/51506542/122950417-0eb37b80-d39a-11eb-8246-030e6de773be.png">

**Comment by hkumar0132** [comment]
Since @AkshatJindal1 is working on this issue, I will work on some others.

**Comment by ming-tsai** [comment]
Ok
