### ISSUE TITLE
Some static pages are not jumping into the correct page as markdown

### ISSUE THREAD

**Issue by ming-tsai** [MakeContributions/markdown-dungeon#28]
The markdown is jumping into the right page, but the static page that is generated by Gatsby is not working using relative link, example, in the **normal-dungeon/1/2-1A.md**, if selected option **Forget it** should jump into **normal-dungeon/2/1.md**, but on the static page is trying to jump into **normal-dungeon/1/2/1**

**✔ Definition of done:**
Every page that is trying to jump into another floor, should work fine on the static page.

**Comment by AudreyKj** [comment]
hello! Can I work on this?

**Comment by ming-tsai** [comment]
Yes @AudreyKj, you could do it.

**Comment by ming-tsai** [comment]
Hi @AudreyKj, sorry about this😶 , the issue is working now, but I don't know why.
