### ISSUE TITLE
Improvising README.md

### ISSUE THREAD

**Issue by Arsenic-ATG** [MakeContributions/markdown-dungeon#30]
I was thinking🤔 to compress the 📖[README.md](https://github.com/MakeContributions/markdown-dungeon/blob/master/README.md) so that it become easier to read for the users, but I want suggestions on how to do it or should not do it at all.

1.  should I break the main file in multiple file (one for contributing instructions, one for installation instructions etc) and link them in the main readme.md file

2. <details><summary>or</summary>should I use a drop down menu like this one</details>

3. or something else....(your suggestion)🤔

**Comment by ming-tsai** [comment]
Hi @Arsenic-ATG,
The seconds one is ok.

**Comment by Arsenic-ATG** [comment]
@ming-tsai thanks for suggestion
I have used that method to compress the readme.md, you can see the the changes on [my fork](https://github.com/Arsenic-ATG/markdown-dungeon/tree/readme_patch) to get an rough idea how things will look after changes.

there is still some 🛠formatting left to do before launching a PR.

any suggestions would be appreciated.🙂
