### ISSUE TITLE
Create a home screen for the game

### ISSUE THREAD

**Issue by VJ1224** [MakeContributions/markdown-dungeon#5]
In english/normal-dungeon there is no markdown file to give a basic description about the game. It directly shows the floor folders which lead to the game starting. A home screen would have a start game and exit game button as well as some help information (how-to-play, about etc.)

**Comment by VJ1224** [comment]
Maybe the start-new-game.md file could be edited to include some of this.

**Comment by ming-tsai** [comment]
Hi @VJ1224, it is nice suggestions, we will work on it, or do you want to help us?

**Comment by VJ1224** [comment]
Sure, I'll start with editing the start-new-game.md file
